### ISSUE TITLE
Support multiple tags at once

### ISSUE THREAD

**Issue by odrotbohm** [StarBax89/alfredworkflow.addatag#1]
First of all: great workflow. I was surprise there hasn't been anything comparable so far.

Is there a chance, the algorithm get's tweaked so that multiple tags can be assigned at once?

`ftag foo bar`

could assign both `foo` and `bar` as tags.

**Comment by StarBax89** [comment]
Hi, I'll put that on my to-do list. =)

**Comment by StarBax89** [comment]
I looked this up in Tag,
you can add multiple comma seperated tags. 
Use
ftag foo,bar

Regards ;)

**Comment by odrotbohm** [comment]
Brilliant, thanks!
